### PR TITLE
Update gem with a bunch of cleanups.

### PR DESCRIPTION
**Pull request by lcpriest**
Hey guys, I was just reading through our fork and we don't have anything too crazy, any interest in merging some or all of this back into master?

Happy to remove breaking changes (Shippingaddress to ShippingAddress etc).

### CODE REVIEW

**Comment by ideaoforder** [comment]
I just did a quick review, and these changes all look good! I'm fine with the shipping_address change, since BigCommerce changed this in their API (without changing the version, and without notifying developers). Your update is now the correct format.

The old URL I'd used must be aliased, because the current gem doesn't seem to be broken (we're using it in production, with no problems).

Could you add in an alias/method to Order.rb so that @order.shippingaddresses still works--just to keep things mostly working for folks (I know the model name is also changed, but that's much less likely to affect folks--even so, I'll add a note before pushing a proper release).

Thanks!

**Comment by lcpriest** [comment]
Updated!

**Comment by lcpriest** [comment]
@ideaoforder is there any other update you need?

**Comment by ideaoforder** [comment]
Nope—I’ll test it locally today, if I can, and then publish.

**Comment by lcpriest** [comment]
@ideaoforder anything holding this back?

**Comment by lcpriest** [comment]
@ideaoforder anything holding this back?

**Comment by ideaoforder** [comment]
Sorry for the colossal delay in merging this. I've also released this on RubyGems as 0.7.0 if you want to move over to using the official gem.

Thanks for all the great work on this!

**Comment by lcpriest** [comment]
Absolutely no worries!

**Pull request merged**
